# This is a basic workflow to help you get started with Actions

name: called workflow with token

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      global: 
        required: true
        type: boolean
      name:
        required: true
        type: string
      email:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
       token:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
      runs-on: ubuntu-20.04
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      steps:
        - uses: actions/checkout@v2

      # Runs a single command using the runners shell
        - name: login github registry
          uses: actions/labeler@v4
          with:
            token: ${{secrets.GIT_CREDENTIALS}}
      
