# This is a basic workflow to help you get started with Actions

name: calling a workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      file_name: 
        required: true
        type: string
      tag:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: login github registry
        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}
      
