# This is a basic workflow to help you get started with Actions

name: called workflow with token

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      servers:
        required: true
        type: string

jobs:
  publish:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - name: login github registry
          shell: pwsh
          run: |
            if(${{ inputs.servers }}.length -ne 0){
               $server = ${{ inputs.servers }}
               }
                
      
