# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: giving github credentials
    uses: chaithragudimalla/WorkFlow/.github/workflows/my_CI_CD.yml@main
    with:
      username: 'chaithragudimalla'
    secrets:
       credentials: ${{ secrets.GIT_CREDENTIAL_PASSWORD }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
           
      # Runs a single command using the runners shell
      - name: Running powershell script
        run: pwsh -c 'invoke-webrequest -URI "https://github.com/chaithragudimalla/WorkFlow/blob/main/main.py" -outfile "main.py"'

      # Runs a set of commands using the runners shell
      - name: uploading to artifact
        uses: actions/upload-artifact@v3.1.0
        with:
           name: 'main.py'
           path: '/home/runner/work/WorkFlow/WorkFlow/main.py'
