name: main
on:
  workflow_dispatch:
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
         - name: check1
           id: check1
           run: echo "check1"
   job2:
      runs-on: ubuntu-latest
      steps:
         - name: check2
           id: check2
           run: echo "check2"
   job3:
     runs-on: ubuntu-latest
     steps:
        - name: check3
          id: check3
          run: echo "check3"
   quality:
      if: job.job1.steps.id == check3 || job.job2.steps.id == check3 || job.job3.steps.id == check3
