# This is a basic workflow to help you get started with Actions
name: new workflow for CI/CD

# Controls when the workflow will run
on:
  workflow_call:
        inputs:
            username:
               required: true
               type: string
        secrets:
            credentials:
                  required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: to login github
        uses: de-vri-es/setup-git-credentials@v2
        with:
          username: 'chaithra'
          credentials: ${{ secrets.GIT_CREDENTIAL_PASSWORD }}

 
