# This is a basic workflow to help you get started with Actions
name: PowerShell-Installation
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Installing PowerShell on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          sudo wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt-get install -y powershell 
      # Runs a set of commands using the runners shell
      - name: testing powershell
        run: pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/WorkFlow/blob/main/main.py" -OutFile "main.py"'
      - name: installing python
        run: |
           sudo apt-get update
           sudo apt-get install software-properties-common
           sudo add-apt-repository ppa:deadsnakes/ppa
           sudo apt-get update
           sudo apt-get install python3
      - name: Installing pip and other modules
        run: |
           pip install pafy
           pip install youtube-dl
           pip install python-vlc
      - name: running python script
        run: python main.py
