name: just testing
on:
  push:
     branches:
         - main
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
         - name: creating a text file
           run: |
              echo 'hello'  > file.txt
         - name: displaying the file
           run: cat file.txt
         - name: downloading file
           run: |
              pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile" -OutFile "Dockerfile"'
         - name: displaying downloaded file
           run: cat Dockerfile
           
