name: just testing
on:
  push:
     branches:
         - main
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
         - name: creating a text file
           run: |
              echo 'hello'  > file.txt
         - name: displaying the file
           run: cat file.txt
         - name: downloading file
           run: |
              pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile" -OutFile "Dockerfile"'
         - name: displaying downloaded file
           run: cat Dockerfile
         - name: downloading another github file
           run: |
              pwsh -command 'Invoke-WebRequest -Uri "https://gist.github.com/pdashford/2e4bcd4fc2343e2fd03efe4da17f577d" -OutFile "gh-download.py"'
         - name: displaying downloaded file
           run: cat gh-download.py
         - name: downloading another file not from github
           run: |
             pwsh -command 'Invoke-WebRequest -Uri "https://drive.google.com/file/d/1HfQhqy6eCTMzmjifXfWk0wrIMdpNOPpQ/view?usp=sharing" -OutFile "pro2.py"'
         - name: displaying the file
           run: cat pro2.py
           
